CREATE TABLE ${target_schema}.objects (
	object_id int8 NOT NULL,
	object_name text NOT NULL,
	object_desc text NULL,
	extraction_type text NULL,
	load_type text NULL,
	merge_key _text NULL,
	delta_field text NULL,
	delta_field_format text NULL,
	delta_safety_period interval NULL DEFAULT '00:00:00'::interval,
	bdate_field text NULL,
	bdate_field_format text NULL,
	bdate_safety_period interval NULL DEFAULT '00:00:00'::interval,
	load_method text NULL,
	job_name text NULL,
	responsible_mail _text NULL,
	priority int4 NULL,
	periodicity interval NULL,
	load_interval interval NULL,
	activitystart time NULL,
	activityend time NULL,
	active bool NULL DEFAULT true,
	load_start_date timestamp NULL DEFAULT '2000-01-01 00:00:00'::timestamp without time zone,
	delta_start_date timestamp NULL DEFAULT '2000-01-01 00:00:00'::timestamp without time zone,
	delta_mode text NULL,
	connect_string text NULL,
	load_function_name text NULL,
	where_clause text NULL,
	load_group text NULL,
	src_date_type text NULL,
	src_ts_type text NULL,
	column_name_mapping jsonb NULL,
	transform_mapping jsonb NULL,
	delta_field_type text NULL,
	bdate_field_type text NULL,
	CONSTRAINT pk_object_id PRIMARY KEY (object_id),
	CONSTRAINT fk_delta_mode FOREIGN KEY (delta_mode) REFERENCES ${target_schema}.d_delta_mode(delta_mode),
	CONSTRAINT fk_extraction_type FOREIGN KEY (extraction_type) REFERENCES ${target_schema}.d_extraction_type(extraction_type),
	CONSTRAINT fk_load_group FOREIGN KEY (load_group) REFERENCES ${target_schema}.d_load_group(load_group),
	CONSTRAINT fk_load_method FOREIGN KEY (load_method) REFERENCES ${target_schema}.d_load_method(load_method),
	CONSTRAINT fk_load_type FOREIGN KEY (load_type) REFERENCES ${target_schema}.d_load_type(load_type)
)
DISTRIBUTED REPLICATED;

-- Table Rules

CREATE RULE objects_delete AS
    ON DELETE TO ${target_schema}.objects DO  INSERT INTO ${target_schema}.objects_log (object_id, object_name, object_desc, extraction_type, load_type, merge_key, delta_field, delta_field_format, delta_safety_period, bdate_field, bdate_field_format, bdate_safety_period, load_method, job_name, responsible_mail, priority, periodicity, load_interval, activitystart, activityend, active, load_start_date, delta_start_date, delta_mode, connect_string, load_function_name, where_clause, load_group, src_date_type, src_ts_type, column_name_mapping, transform_mapping, delta_field_type, bdate_field_type, change_type, change_timestamp, change_username)  SELECT old.object_id,
            old.object_name,
            old.object_desc,
            old.extraction_type,
            old.load_type,
            old.merge_key,
            old.delta_field,
            old.delta_field_format,
            old.delta_safety_period,
            old.bdate_field,
            old.bdate_field_format,
            old.bdate_safety_period,
            old.load_method,
            old.job_name,
            old.responsible_mail,
            old.priority,
            old.periodicity,
            old.load_interval,
            old.activitystart,
            old.activityend,
            old.active,
            old.load_start_date,
            old.delta_start_date,
            old.delta_mode,
            old.connect_string,
            old.load_function_name,
            old.where_clause,
            old.load_group,
            old.src_date_type,
            old.src_ts_type,
            old.column_name_mapping,
            old.transform_mapping,
            old.delta_field_type,
            old.bdate_field_type,
            'delete'::text AS text,
            now() AS now,
            "current_user"() AS "current_user";

CREATE RULE objects_insert AS
    ON INSERT TO ${target_schema}.objects DO  INSERT INTO ${target_schema}.objects_log (object_id, object_name, object_desc, extraction_type, load_type, merge_key, delta_field, delta_field_format, delta_safety_period, bdate_field, bdate_field_format, bdate_safety_period, load_method, job_name, responsible_mail, priority, periodicity, load_interval, activitystart, activityend, active, load_start_date, delta_start_date, delta_mode, connect_string, load_function_name, where_clause, load_group, src_date_type, src_ts_type, column_name_mapping, transform_mapping, delta_field_type, bdate_field_type, change_type, change_timestamp, change_username)  SELECT new.object_id,
            new.object_name,
            new.object_desc,
            new.extraction_type,
            new.load_type,
            new.merge_key,
            new.delta_field,
            new.delta_field_format,
            new.delta_safety_period,
            new.bdate_field,
            new.bdate_field_format,
            new.bdate_safety_period,
            new.load_method,
            new.job_name,
            new.responsible_mail,
            new.priority,
            new.periodicity,
            new.load_interval,
            new.activitystart,
            new.activityend,
            new.active,
            new.load_start_date,
            new.delta_start_date,
            new.delta_mode,
            new.connect_string,
            new.load_function_name,
            new.where_clause,
            new.load_group,
            new.src_date_type,
            new.src_ts_type,
            new.column_name_mapping,
            new.transform_mapping,
            new.delta_field_type,
            new.bdate_field_type,
            'insert'::text AS text,
            now() AS now,
            "current_user"() AS "current_user";

CREATE RULE objects_update AS
    ON UPDATE TO ${target_schema}.objects DO  INSERT INTO ${target_schema}.objects_log (object_id, object_name, object_desc, extraction_type, load_type, merge_key, delta_field, delta_field_format, delta_safety_period, bdate_field, bdate_field_format, bdate_safety_period, load_method, job_name, responsible_mail, priority, periodicity, load_interval, activitystart, activityend, active, load_start_date, delta_start_date, delta_mode, connect_string, load_function_name, where_clause, load_group, src_date_type, src_ts_type, column_name_mapping, transform_mapping, delta_field_type, bdate_field_type, change_type, change_timestamp, change_username)  SELECT old.object_id,
            old.object_name,
            old.object_desc,
            old.extraction_type,
            old.load_type,
            old.merge_key,
            old.delta_field,
            old.delta_field_format,
            old.delta_safety_period,
            old.bdate_field,
            old.bdate_field_format,
            old.bdate_safety_period,
            old.load_method,
            old.job_name,
            old.responsible_mail,
            old.priority,
            old.periodicity,
            old.load_interval,
            old.activitystart,
            old.activityend,
            old.active,
            old.load_start_date,
            old.delta_start_date,
            old.delta_mode,
            old.connect_string,
            old.load_function_name,
            old.where_clause,
            old.load_group,
            old.src_date_type,
            old.src_ts_type,
            old.column_name_mapping,
            old.transform_mapping,
            old.delta_field_type,
            old.bdate_field_type,
            'update'::text AS text,
            now() AS now,
            "current_user"() AS "current_user";


-- Permissions

ALTER TABLE ${target_schema}.objects OWNER TO "${owner}";
GRANT ALL ON TABLE ${target_schema}.objects TO "${owner}";